[package]
name = "rustcache-client"
version = "0.1.0"
authors = ["Miguel Lattuada <miguellattuada@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
